name: building_beautiful_app_with_flutter
description: Building a beautiful app with Flutter.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  covid19:
    path: packages/covid19
  charts_flutter:
  flare_flutter:
  flutter:
    sdk: flutter
  flutter_svg:
  flutter_widget_from_html:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit:

flutter:
  assets:
    - images/
  uses-material-design: true
